/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NpmPackageList: typeof import('./../components/integrations/NpmPackageList.vue')['default']
    PackageTags: typeof import('./../components/ui/PackageTags.vue')['default']
  }
}
