name: Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Generate JSON
        run: |
          npm run generate-data
          cp public/npm-data.json dist/npm-data.json
          cp public/wakatime-data.json dist/wakatime-data.json

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: false
          force_orphan: true
